title: 专注于Java Web
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: ""
#baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url:  # the base hostname & protocol for your site, e.g. http://example.com
blog: http://lframe.cn/ #if your site has a twitter account, enter it here

# Author Settings
author: 梁志宇 # add your name
author-img: david-freeman.jpg # add your photo
about-author: 我是一名Java Web 工程师，专注于Java 后端. # 用于修改名字下面的描述信息
#twitter:  # add your Twitter handle
facebook: # add your Facebook handle
github: liangFrame # add your Github handle
linkedin: # add your Linkedin handle
email: 605415633@qq.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
